server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: file:///Users/junyounglee/project/jpa_study/section4/git-local-repo
          uri: https://github.com/qlqhtlrrl4/spring-cloud-config
          